### PR TITLE
KAS-3520: government fields register

### PR DESCRIPTION
**Pull request by sergiofenoll**
https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/316

Small tweak to two URIs

### CODE REVIEW

**Review by tdn — COMMENTED** [review]
Any particular reason we need to change this to the English variant?

Since https://github.com/kanselarij-vlaanderen/kaleidos-documentation/blob/master/data-model/uri-formatting.md specifies "The concept name must always be lowercase, singular, and in Dutch".

Edit: huh. I see we use 'scheme' for the mandatees, but we do use 'schema' in the resource base https://github.com/kanselarij-vlaanderen/app-kaleidos/blob/development/config/resources/concept-domain.json#L82

**Comment by sergiofenoll** [comment]
Ah, I didn't realize that! I based myself off what seems to be used in Themis, e.g.: https://themis.vlaanderen.be/id/concept-scheme/e93481b2-342d-468b-8def-2d629232d3a5 (though this might also be the exception rather than the rule).

In any case this is a super minor change, I can just close this PR and revert the changes in the backend.

**Review by tdn — APPROVED** [review]
Apparently `concept-scheme` is what we're using most frequently, so if we want to change that, let's do it in a different story for all data. So this one can go through

**Comment by erikap** [comment]
> Apparently `concept-scheme` is what we're using most frequently, so if we want to change that, let's do it in a different story for all data. So this one can go through

We need to take care for concept-schemes that have already been published on Themis. We cannot just change the URI for those ones.

**Pull request merged**
