### PR TITLE
Feature/kas 3771 dependencies

### PR DESCRIPTION
**Pull request by ValenberghsSven**
https://kanselarij.atlassian.net/browse/KAS-3771

Draft.
Checking when or if test are failing because of version bumps.
1st run:
bumped `ember-promise-helpers` to most recent
removed `@lblod/ember-rdfa-editor-plugin-system-dispatcher`, archived, should be fine with newer version of editor
removed `ember-maybe-import-regenerator` was pointless since it does nothing if we have `includePolyfill: true`
replaced `ember-cli-sanitize-html` with `sanitize-html` and custom octane component (the package only had 1 component)

note: it is possible jenkins does not play nice with small bumps in npm and gets previous cached npm cached. Unsure of how all that works precisely...

### CODE REVIEW

**Comment by ValenberghsSven** [comment]
our own fork https://github.com/erikap/ember-attacher
Can be removed if no other repo uses this.
Removed dependency in this PR

**Comment by ValenberghsSven** [comment]
Deployed this feature branch on ACC to test acmidm and seems to work.
No more babel warnings on startup.

**Review by erikap — APPROVED** [review]

**Comment by ValenberghsSven** [comment]
some tests are failing, trying to fix them.
It's a bit weird that I had a green run at one point, then I changed the jquery flag and the acmidm package.
Unsure what is happening

**Comment by ValenberghsSven** [comment]
made small changes to jenkins to only run a few specs for faster results.
Reverted the jquery integration flag back to true and it seems to work better.
Is Jquery being used somewhere without explicit injection?

Going to remove the flag again and add the jquery package to see if it that makes a difference.

**Comment by ValenberghsSven** [comment]
update, looking at the logs and screenshots, it seems that mandatees are not always loading.
Looking deeper, it seems that the migrations service is building the DB from scratch (so all migrations)
Unsure why the zip is not being used.

**Comment by ValenberghsSven** [comment]
finally a green PR without the jquery thing, merging this one.

**Pull request merged**
