### PR TITLE
KAS-3770: Set not formally ok when changing government fields

### PR DESCRIPTION
**Pull request by sergiofenoll**
When editing the government fields of an agendaitem (both from the agendaitem view and the subcase view), changing the government fields will cause the agendaitem to no longer be formally Ok

### CODE REVIEW

**Review by erikap — APPROVED** [review]

**Comment by erikap** [comment]
Some of the failing tests seem related to this PR. Can you have a look @sergiofenoll ?

**Comment by erikap** [comment]
> Some of the failing tests seem related to this PR. Can you have a look @sergiofenoll ?

Sorry, not sure, as this PR only affects government domain changes, not mandatee changes :thinking:

**Comment by sergiofenoll** [comment]
> > Some of the failing tests seem related to this PR. Can you have a look @sergiofenoll ?
> 
> Sorry, not sure, as this PR only affects government domain changes, not mandatee changes thinking

Gonna have a look :mag:

**Comment by erikap** [comment]
@sergiofenoll I see similar failures on https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1578 so probably nothing to do with this PR...

**Comment by sergiofenoll** [comment]
Looking at the request going out, when saving the mandatees on the agendaitem the request body only contains the 2 mandatees already set on the agendaitem, not the 3 set by the test. 

I think the failing tests are related to the refactor of the `ModelWithModifier`, because if I revert the frontend to v5.41.2 (before the refactor), the mandatee tests pass. I'm not sure why though, will have to investigate some more.

**Pull request merged**
