### PR TITLE
Feature/KAS-4403 Don't choke on unparseable piece names when generating betreft

### PR DESCRIPTION
**Pull request by sergiofenoll**
https://kanselarij.atlassian.net/browse/KAS-4403

If a piece name can't be parsed we just add it as is.

### CODE REVIEW

**Comment by sergiofenoll** [comment]
Crap, I branched off development here. Can we cherry pick this commit if we're going straight to ACC?

**Comment by ValenberghsSven** [comment]
> Crap, I branched off development here. Can we cherry pick this commit if we're going straight to ACC?

should be able to

**Review by ValenberghsSven — APPROVED** [review]
Should be fine.
Is this urgent for ACC?
If yes > cherry-pick.
If no > merge

**Review by tdn — APPROVED** [review]
Can go to `development`. We'll do a re-release

**Pull request merged**
