### PR TITLE
KAS-2429 Use Themis URIs for vergaderactiviteit types

### PR DESCRIPTION
**Pull request by sergiofenoll**
Backend PR: https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/271

### CODE REVIEW

**Comment by sergiofenoll** [comment]
custom jenkins build: http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/190/

**Comment by sergiofenoll** [comment]
For the tests to pass on this one, we'll need an updated version of session-number-service. This would mean merging this PR https://github.com/kanselarij-vlaanderen/session-number-service/pull/7 first, bump the docker image version, and update the backend PR before being able to successfully do a test run. Because we're getting rid of said service in a different PR, I decided to commit a change to use mu-cl-resources to fetch the closest meeting instead of using said service.

Since this isn't technically part of this PR, it can be reverted before merging if desired.

**Comment by erikap** [comment]
> For the tests to pass on this one, we'll need an updated version of session-number-service. This would mean merging this PR [kanselarij-vlaanderen/session-number-service#7](https://github.com/kanselarij-vlaanderen/session-number-service/pull/7) first, bump the docker image version, and update the backend PR before being able to successfully do a test run. Because we're getting rid of said service in a different PR, I decided to commit a change to use mu-cl-resources to fetch the closest meeting instead of using said service.
> 
> Since this isn't technically part of this PR, it can be reverted before merging if desired.

Ok for me to embed the change for `fetchClosestMeetingAndAgendaId` in this PR, but then it's probably best to embed the removal of the session-number-service in the backend PR as well?

**Comment by sergiofenoll** [comment]
> > For the tests to pass on this one, we'll need an updated version of session-number-service. This would mean merging this PR [kanselarij-vlaanderen/session-number-service#7](https://github.com/kanselarij-vlaanderen/session-number-service/pull/7) first, bump the docker image version, and update the backend PR before being able to successfully do a test run. Because we're getting rid of said service in a different PR, I decided to commit a change to use mu-cl-resources to fetch the closest meeting instead of using said service.
> > Since this isn't technically part of this PR, it can be reverted before merging if desired.
> 
> Ok for me to embed the change for `fetchClosestMeetingAndAgendaId` in this PR, but then it's probably best to embed the removal of the session-number-service in the backend PR as well?

I don't think that'd be feasible. Removing the session-number service happens in #1289, where we make the exact same change as we do here (replace `/fetchClosestMeeting` with a call to mu-cl-resources). But that PR depends on #1288 because that's where we remove the need for `/activeAgendas`. So we'd have to merge #1288 before being able to fully remove the service from the backend.

**Comment by sergiofenoll** [comment]
jenkins build with updated migration: http://kal-kastaar.s.redpencil.io:8080/job/kaleidos/job/custom_frontend_backend_combination/193/

**Review by erikap — APPROVED** [review]

**Pull request merged**
