### PR TITLE
KAS-3690 add plausible package and config and setup in application route

### PR DESCRIPTION
**Pull request by ValenberghsSven**
https://kanselarij.atlassian.net/browse/KAS-3690

- implementing plausible (done I think? custom events and goals out of scope)
- removing matomo (not done, don't we want to run both analytics in parallel for accuracy?)
- testing (I don't have a plausible login that I know of, how does one connect with the api host)

### CODE REVIEW

**Review by erikap — COMMENTED** [review]
Plausible setup looks good :+1: 

Env vars to be used (for production) are
```
      EMBER_ANALYTICS_APP_DOMAIN: "kaleidos.vlaanderen.be"
      EMBER_ANALYTICS_API_HOST: "https://plausible.kanselarij.org"
```

Business has decided to go for Plausible and not Matomo. No need to run both in parallel. The Matomo config/setup can be removed from the app.

**Comment by ValenberghsSven** [comment]
> Business has decided to go for Plausible and not Matomo. No need to run both in parallel. The Matomo config/setup can be removed from the app

That is everything regarding "matomo" or "metrics" so ember-metrics, ember-metrics-matomo-adapter and all `@service metrics`?
Will do tomorrow.

**Comment by ValenberghsSven** [comment]
1 question regarding the setup. 
I put the plausible setup in the `constructor` because that was were the matomo setup was.
I saw other apps put it in the `beforeModel`.
I guess that as long as it gets called, it should be fine

**Comment by ValenberghsSven** [comment]
only failing test is a flaky one.

**Review by erikap — APPROVED** [review]

**Comment by erikap** [comment]
> 1 question regarding the setup. I put the plausible setup in the `constructor` because that was were the matomo setup was. I saw other apps put it in the `beforeModel`. I guess that as long as it gets called, it should be fine

Constructor is OK.  To do it the Ember-way it should be done in [an application instance initializer](https://guides.emberjs.com/release/applications/initializers/#toc_application-instance-initializers) (same holds for `moment` and `intl` setup) but let's consider that out of scope of this story.

**Pull request merged**
