### PR TITLE
KAS-4622: Verwijdering van Auk::Label + opkuis van alle SCSS/styling mbt auk-label

### PR DESCRIPTION
**Pull request by brenner-company**
**Tickets binnen Jira:** 
- https://kanselarij.atlassian.net/browse/KAS-4622

⚠️ ~~Voor dat deze story gemerged mag worden, moet eerst https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/2079 er door zijn.~~

⚠️ Moet op zich niet echt gereviewed worden, maar alle tests moeten wel volledig ok zijn om te weten dat er geen functionele impact is.

### CODE REVIEW

**Review by ValenberghsSven — APPROVED** [review]
All green.
We should have a change in package-lock with the css package bump?

**Comment by brenner-company** [comment]
> All green. We should have a change in package-lock with the css package bump?

Wasn't sure if we need to commit those file changes again 😅 I'll do that first thing tomorrow.

**Comment by ValenberghsSven** [comment]
> > All green. We should have a change in package-lock with the css package bump?
> 
> Wasn't sure if we need to commit those file changes again 😅 I'll do that first thing tomorrow.

Afraid we do.
conflict solving will be a pain. but the best strategy for complex merges will be to just purge the file and recreate it.
And make sure everyone is on the same npm version (or at least not an old version. Those make lock files in a different way, resulting in a different version of the lock file)

**Comment by brenner-company** [comment]
> > > All green. We should have a change in package-lock with the css package bump?
> > 
> > 
> > Wasn't sure if we need to commit those file changes again 😅 I'll do that first thing tomorrow.
> 
> Afraid we do. conflict solving will be a pain. but the best strategy for complex merges will be to just purge the file and recreate it. And make sure everyone is on the same npm version (or at least not an old version. Those make lock files in a different way, resulting in a different version of the lock file)

No problem. I've committed the changes to the package-lock file. Seems good to go ✅

**Pull request merged**
